spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playplace?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            #            redirect-uri: "https://playplace.co.kr/login/oauth2/code/google"
            redirect-uri: "https://playplace.co.kr/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
  cloud:
    gcp:
      project-id: playplace
      credentials:
        location: classpath:playplace-c109-63af6b6b49fd.json
jwt:
  secret: ${JWT_SECRET}
openai:
  api-key: ${OPENAPI_KEY}
